### ISSUE TITLE
Adding function for Max discount in default coupon

### ISSUE THREAD

**Issue by Khnaz35** [akmjoe/opencart-coupon-advanced#1]
Hi, 
Do you have plan to add Max discount option for coupon ?
Let say discount is $10 so when a customer buy the item for 100$ so discount is 10 and when buy for 200$ discount becomes 20. 
But if we define limit for max discount 15 so when customer will buy for 200$ the discount still should be max 15 only not 20.

**Comment by akmjoe** [comment]
I will see what I can do. Should be easy to add.

**Comment by Khnaz35** [comment]
Hi do you have any plan when you will push these changes?

**Comment by akmjoe** [comment]
I added this setting and briefly tested it. I would recommend testing to make sure it works the way you want.

**Comment by Khnaz35** [comment]
Thanks will check it and report back incase if i run into any issues. Can i apply same changes to default coupon extension in OC.

**Comment by Khnaz35** [comment]
I have tried to install extension on fresh install, the extension is not able to install this time so can't test the changes.
